#!/bin/bash
AVD=test-emulator
CONFIG_FILE=/root/.android/avd/test-emulator.avd/config.ini

sed -i -e 's/hw.ramSize=.*/hw.ramSize=2048/;s/vm.heapSize=.*/vm.heapSize=128/' $CONFIG_FILE

emulator -force-32bit -avd $AVD -no-skin -no-audio -no-window -no-boot-anim &
wait-for-emulator 
